Added a friendly curl error message (for the trillianth time)

diff --git a/utils/functions b/utils/functions
--- a/utils/functions
+++ b/utils/functions
@@ -7,6 +7,11 @@ cache() {
   if ! [ -e $DEST ]; then
     mkdir -p $(dirname $DEST)
     curl -o $DEST $1
+
+	if [ $? -ne 0 ]; then
+		>&2 echo "CURL exited with nonzero exit code, which probably means it could not download and cache a file: $1 --> $DEST"
+		exit 1
+	fi
   fi
   echo $DEST
 }
